version: "3.8"

services:
  server:
    build:
      context: ./server # Relative path to server folder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: always

  client:
    build:
      context: ./client # Relative path to client folder
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/usr/src/app
    restart: always
