services:
  server:
    build:
      context: ./server # Correct context for server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client # Correct context for client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
